// src/routes/__layout.svelte
<!-- This file defines the required USC banner that shows on the top of all pages -->
<script lang="ts">
	import '../app.css';
	import Logo from '../images/usc-shield-name-white.png?webp';
</script>

<div class="bg-black h-[60px]">
	<a
		rel="external"
		href="https://www.usc.edu/"
		referrerpolicy="no-referrer"
		class="float-right h-[60px] w-[198px] p-[11px]"
	>
		<img src={Logo} alt="USC Logo" />
	</a>
</div>

<slot />

// components/layout.tsx
import { NextPage } from "next";

const Layout: NextPage = ({ children }) => {
  return (
    <>
      <div id="usc-banner" className="bg-black overflow-auto">
        <a className="float-right">
          <img
            src={require("../images/usc-shield-name-white.png")}
            className="h-[38px] w-[176px] m-[11px]"
            alt="USC Logo"
          />
        </a>
      </div>
      <main>{children}</main>
    </>
  );
};

export default Layout;
